# -*- coding: utf-8 -*-
"""Bitcoin_Market_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUqHhUcagMg27fA7KhqAPnNc6squ9aox
"""

import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv("historical_data.csv")
df2 = pd.read_csv("fear_greed_index.csv")

df1["Timestamp IST"] = pd.to_datetime(
    df1["Timestamp IST"],
    dayfirst=True
)

df1["Date"] = df1["Timestamp IST"].dt.date

df2["date"] = pd.to_datetime(df2["date"]).dt.date

df = pd.merge(
    df1,
    df2,
    left_on="Date",
    right_on="date",
    how="left"
)

df.head()

#Check missing values
df.isnull().sum()

#Average Profit/Loss by Market Sentiment
df.groupby("classification")["Closed PnL"].mean()

#Number of Trades
df["classification"].value_counts()

# Plot 1
df.groupby("classification")["Closed PnL"].mean().plot(kind="bar")
plt.title("Average Closed PnL")
plt.show()

# Plot 2
df["classification"].value_counts().plot(kind="pie", autopct="%1.1f%%")
plt.ylabel("")
plt.show()

df.columns

"""## Observations

1. Trader profit changes with different market sentiments.
2. The number of trades varies during Fear, Greed, and Neutral market conditions.
3. The analysis shows that market sentiment influences trading behaviour.
4. These insights can help understand trader performance under different market conditions.

## Conclusion

By combining trading data with the Fear & Greed Index, we can observe how market sentiment affects trader behaviour and profitability. Such analysis can support better trading decisions.
"""